---
- name: Restore my personal Linux system
  hosts: localhost
  connection: local
  become: yes

  vars_files:
    - "{{ config_file | default('system_config.yml') }}"

  tasks:
    # Display system metadata
    - name: Display system metadata
      debug:
        msg: |
          Restoring configuration for:
          System: {{ system_config.metadata.hostname }}
          OS: {{ system_config.metadata.os_name }} {{ system_config.metadata.os_version }}
          Backup Date: {{ system_config.metadata.timestamp }}
      tags: always

    # Mount Points
    - name: Restore mount points
      mount:
        path: "{{ item.mountpoint }}"
        src: "{{ item.src }}"
        fstype: "{{ item.fstype }}"
        state: mounted
      loop: "{{ system_config.mounts }}"
      tags: mounts

    # Symlinks
    - name: Restore symlinks
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ system_config.symlinks }}"
      become: no
      tags: symlinks

    # Packages
    - name: Install packages
      package:
        name: "{{ system_config.packages }}"
        state: present
      tags: packages

    # Services
    - name: Ensure services are running
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ system_config.services }}"
      tags: services

    # Cron Jobs
    - name: Restore cron jobs
      command: crontab {{ config_file | dirname }}/{{ item.file }}
      args:
        chdir: "{{ config_file | dirname }}"
      loop: "{{ system_config.cron_jobs }}"
      become: no
      become_user: "{{ item.user }}"
      when: item.file is defined
      tags: cron

    # Firewall Rules (manual review recommended)
    - name: Display firewall rules for manual restoration
      debug:
        msg: "Please manually restore firewall rules:\n{{ system_config.firewall_rules }}"
      tags: firewall

    # Dotfiles
    - name: Restore dotfiles
      copy:
        src: "{{ item }}"
        dest: "{{ item }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
      loop: "{{ system_config.dotfiles }}"
      become: no
      tags: dotfiles

    # Command Outputs (manual review recommended)
    - name: Display command outputs for manual review
      debug:
        msg: |
          The following command outputs were captured for reference:
          {% for output in system_config.command_outputs %}
          - {{ output.command }}: {{ config_file | dirname }}/{{ output.file }}
          {% endfor %}
          Please review these files for manual restoration or system verification.
      when: system_config.command_outputs | length > 0
      tags: command_outputs